services:
  ztlog-admin:
    image: ${DOCKERHUB_USERNAME}/ztlog-admin
    container_name: ztlog-admin
    ports:
      - "${ADM_PORT}:${ADM_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: ${ENV}
      SERVER_PORT: ${ADM_PORT}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY:-}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY:-}
      JAVA_OPTS: -Xmx256M -Xms256M
      LOG_PATH: /app/logs
    volumes:
      - ./logs/admin:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        tag: "{{.Name}}"

  ztlog-api:
    image: ${DOCKERHUB_USERNAME}/ztlog-api
    container_name: ztlog-api
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: ${ENV}
      SERVER_PORT: ${API_PORT}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY:-}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY:-}
      JAVA_OPTS: -Xmx256M -Xms256M
      LOG_PATH: /app/logs
    volumes:
      - ./logs/api:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        tag: "{{.Name}}"
